'use client';
import { useEffect, useState } from 'react';
import Welcome from './welcome';
import {supabase,asset} from '../lib/supabase';
import { Zap, Package, ArrowDownLeft, ArrowUpRight, Plus, Search, SlidersHorizontal, X, LockKeyhole, Download, Mail, RefreshCw, LayoutGrid, List, ChevronRight, Boxes, History, Building2, Check, Pencil, AlertTriangle, LogOut } from 'lucide-react';
const manufacturers=['Schneider Electric','Legrand','Hager','ABB','Siemens','Eaton','Nexans','Wago','Phoenix Contact','Rittal','Gewiss','Delta Dore','Theben','Signify','LEDVANCE','Atlantic','Chauvin Arnoux','Fluke','Socomec','Weidmüller','Legrand Cable Management','3M'];
const distributors=['Rexel','Sonepar','YESSS Électrique','CGED'];
const types=['Protection électrique','Appareillage','Câbles et conducteurs','Éclairage','Automatismes','Tableaux et coffrets','Outillage','Domotique','Cheminement','Énergie et recharge'];
const categories=['Habitat','Tertiaire','Industrie'];
type Item={id:string;ref:string;name:string;type:string;category:string;supplier:string;unit:string;location:string;stock:number;threshold:number};
const empty={items:[] as Item[],movements:[] as any[],totals:[] as any[],settings:null as any,configured:false,admin:false,members:[] as any[]};
const blank={ref:'',name:'',type:types[0],category:categories[0],supplier:manufacturers[0],unit:'pièce',location:'',stock:0,threshold:5};
export default function Store({role}:{role:string}){
 const [memberEmail,setMemberEmail]=useState(''),[memberRole,setMemberRole]=useState('team');
 const [home,setHome]=useState(false);
 const [data,setData]=useState(empty),[online,setOnline]=useState(false),[loaded,setLoaded]=useState(false),[filter,setFilter]=useState({type:'',category:'',supplier:'',search:''}),[tab,setTab]=useState('stock'),[view,setView]=useState('cards'),[modal,setModal]=useState(''),[error,setError]=useState(''),[toast,setToast]=useState(''),[busy,setBusy]=useState(false),[article,setArticle]=useState<any>(blank),[target,setTarget]=useState<Item|null>(null),[kind,setKind]=useState('in'),[quantity,setQuantity]=useState(1),[note,setNote]=useState(''),[email,setEmail]=useState(''),[code,setCode]=useState(''),[confirm,setConfirm]=useState(''),[school,setSchool]=useState({name:'',address:'',logo:''}),[recipient,setRecipient]=useState('');
 async function load(){try{const {data:v,error:e}=await supabase.rpc('melec_store');if(e)throw new globalThis.Error(e.message);setData(v);setOnline(true);setLoaded(true);}catch{setOnline(false);}}
 useEffect(()=>{load();const id=setInterval(load,2000);return()=>clearInterval(id);},[]);
 useEffect(()=>{if(toast){const id=setTimeout(()=>setToast(''),4500);return()=>clearTimeout(id);}},[toast]);
 function open(m:string){setError('');setCode('');setConfirm('');setModal(m);}
 async function mutate(body:any,message:string,close=true){setBusy(true);setError('');try{const {error:e}=await supabase.rpc('melec_mutate',{b:body});if(e)throw new globalThis.Error(e.code==='23505'?'Cette référence existe déjà.':e.message);await load();setToast(message);if(close)setModal('');return true;}catch(e:any){setError(e.message);return false;}finally{setBusy(false);}}
 const selected=!!(filter.type||filter.category||filter.supplier);
 const filtered=data.items.filter(i=>(!filter.type||i.type===filter.type)&&(!filter.category||i.category===filter.category)&&(!filter.supplier||i.supplier===filter.supplier)&&(!filter.search||`${i.name} ${i.ref} ${i.location}`.toLowerCase().includes(filter.search.toLowerCase())));
 const ids=new Set(filtered.map(i=>i.id)),movements=data.movements.filter(m=>ids.has(m.item_id)),totals=data.totals.filter(t=>ids.has(t.item_id));
 const sum=(field:string)=>totals.reduce((s,t)=>s+(t[field]||0),0);
 const suppliers=[...new Set([...manufacturers,...distributors,...data.items.map(i=>i.supplier)])];
 const typeOptions=[...new Set([...types,...data.items.map(i=>i.type)])],categoryOptions=[...new Set([...categories,...data.items.map(i=>i.category)])];
 function adminOpen(){if(role!=='admin'){setToast('Votre compte ne dispose pas des droits administrateur.');return;}setSchool(data.settings||{name:'',address:'',logo:''});open('admin');}
 async function pdf(){const { jsPDF }=await import('jspdf');const p=new jsPDF({orientation:'landscape'});const w=p.internal.pageSize.getWidth(),h=p.internal.pageSize.getHeight();const s=data.settings;let y=18;let page=1;
  const header=()=>{p.setTextColor(26,40,53);p.setFont('helvetica','bold');p.setFontSize(20);p.text(s?.name||'MELECGEST — Inventaire électrique',14,20);p.setFont('helvetica','normal');p.setFontSize(10);if(s?.address){const a=p.splitTextToSize(s.address,220);p.text(a,14,28);y=30+a.length*5;}else y=30;if(s?.logo)p.addImage(s.logo,'JPEG',w-40,10,25,25);p.setTextColor(90,100,110);p.text(`Inventaire du ${new Date().toLocaleString('fr-FR')} • ${filtered.length} référence(s)`,14,y+6);p.text(p.splitTextToSize([filter.type,filter.category,filter.supplier].filter(Boolean).join(' / '),250),14,y+12);y+=24;p.setFillColor(237,242,240);p.rect(14,y,w-28,9,'F');p.setTextColor(26,40,53);p.setFont('helvetica','bold');['Référence','Désignation','Type / catégorie','Fournisseur','Stock','Entrées','Sorties'].forEach((t,i)=>p.text(t,[16,48,120,184,232,251,272][i],y+6));y+=12;p.setFont('helvetica','normal');};
  const footer=()=>{p.setFontSize(9);p.setTextColor(110,120,125);p.text(`MELECGEST • Page ${page}`,14,h-8);};header();for(const i of filtered){const t=data.totals.find(t=>t.item_id===i.id);const cols=[p.splitTextToSize(i.ref,30),p.splitTextToSize(i.name,68),p.splitTextToSize(`${i.type}\n${i.category}`,60),p.splitTextToSize(i.supplier,42),p.splitTextToSize(`${i.stock} ${i.unit}`,17),[String(t?.incoming||0)],[String(t?.outgoing||0)]];const row=Math.max(...cols.map(c=>c.length))*4.5+7;if(y+row>h-16){footer();p.addPage();page++;header();}p.setFontSize(9);p.setTextColor(30,45,55);cols.forEach((c,j)=>p.text(c,[16,48,120,184,232,251,272][j],y+5));y+=row;p.setDrawColor(225,230,232);p.line(14,y,w-14,y);}footer();return p;}
 async function download(){setBusy(true);try{(await pdf()).save('MELECGEST-inventaire.pdf');setToast('Le PDF a été téléchargé.');}catch{setToast('La génération du PDF a échoué.');}finally{setBusy(false);}}
 async function send(e:React.FormEvent){e.preventDefault();setBusy(true);try{const p=await pdf();const file=new File([p.output('blob')],'MELECGEST-inventaire.pdf',{type:'application/pdf'});if(navigator.canShare?.({files:[file]})){await navigator.share({files:[file],title:'Inventaire MELECGEST',text:`Inventaire à transmettre à ${recipient}`});setToast('PDF partagé via votre appareil.');}else{p.save('MELECGEST-inventaire.pdf');window.location.href=`mailto:${encodeURIComponent(recipient)}?subject=${encodeURIComponent('Inventaire électrique — '+(data.settings?.name||'MELECGEST'))}&body=${encodeURIComponent('Bonjour,\n\nVeuillez trouver ci-joint l’inventaire du magasin électrique.\n\nAjoutez le fichier MELECGEST-inventaire.pdf téléchargé à ce message avant de l’envoyer.')}`;setToast('PDF téléchargé : ajoutez-le en pièce jointe au message.');}setModal('');}catch(e:any){setError(e.name==='AbortError'?'Partage annulé.':'Impossible de préparer le PDF.');}finally{setBusy(false);}}
 async function logoUpload(file?:File){if(!file)return;if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>10000000){setError('Choisissez un logo PNG, JPEG ou WebP de moins de 10 Mo.');return;}try{const img=await createImageBitmap(file),canvas=document.createElement('canvas');const r=Math.min(1,500/img.width,500/img.height);canvas.width=img.width*r;canvas.height=img.height*r;const ctx=canvas.getContext('2d')!;ctx.fillStyle='white';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(img,0,0,canvas.width,canvas.height);setSchool(s=>({...s,logo:canvas.toDataURL('image/jpeg',0.85)}));img.close();}catch{setError('Impossible de lire ce logo.');}}
 return <div className={`app ${home?'is-home':'is-store'}`}>{home?<Welcome online={online} onAdmin={adminOpen} onEnter={(category='')=>{setFilter({type:'',category,supplier:'',search:''});setHome(false);window.scrollTo({top:0});}}/>:<><header className="topbar"><a href={asset('')} className="brand"><img className="brand-crest" src={asset('melecgest-crest.png')} alt="Écusson MELECGEST — Gestion du magasin" width="60" height="72"/><span>MELEC<span className="brand-light">GEST</span><small>LE MAGASIN ÉLECTRIQUE</small></span></a><div className="top-actions"><span className={`connection ${online?'':'offline'}`}><i/>{online?'Synchronisé':loaded?'Hors connexion':'Connexion…'}</span>{role==='admin'&&<button className="quiet" aria-label="Administration" onClick={adminOpen}><LockKeyhole size={16}/><span>Administration</span></button>}</div></header>
 <main><div className="breadcrumb"><button className="home-link" onClick={()=>{setHome(true);window.scrollTo({top:0});}}>Accueil</button> <ChevronRight size={13}/> Magasin électrique</div><section className="heading"><div className="heading-identity"><img className="heading-crest" src={asset('melecgest-crest.png')} alt="" aria-hidden="true" width="130" height="154"/><div className="heading-copy"><div className="eyebrow"><span className="eyebrow-line"/> GESTION DU MATÉRIEL ÉLECTRIQUE</div><h1>Votre magasin.  <span>En temps réel.</span></h1><p>Un inventaire organisé. Chaque entrée et sortie enregistrée.</p></div></div><button className="primary" disabled={!online} onClick={()=>{setArticle({...blank});open('article');}}><Plus size={19}/> Nouvel article</button></section>
 <section className="filter-panel"><div className="filter-heading"><span><SlidersHorizontal size={18}/> Explorer le magasin</span><small>Votre inventaire apparaît après une sélection</small></div><div className="filters"><label>Type de matériel<select value={filter.type} onChange={e=>setFilter({...filter,type:e.target.value})}><option value="">Choisir un type</option>{typeOptions.map(v=><option key={v}>{v}</option>)}</select></label><label>Catégorie<select value={filter.category} onChange={e=>setFilter({...filter,category:e.target.value})}><option value="">Choisir une catégorie</option>{categoryOptions.map(v=><option key={v}>{v}</option>)}</select></label><label>Fournisseur / fabricant<select value={filter.supplier} onChange={e=>setFilter({...filter,supplier:e.target.value})}><option value="">Choisir un fournisseur</option><optgroup label="Fabricants">{suppliers.filter(v=>!distributors.includes(v)).map(v=><option key={v}>{v}</option>)}</optgroup><optgroup label="Distributeurs">{distributors.map(v=><option key={v}>{v}</option>)}</optgroup></select></label><label>Rechercher<div className="search-field"><Search size={17}/><input placeholder="Référence, désignation…" value={filter.search} onChange={e=>setFilter({...filter,search:e.target.value})}/></div></label></div>{selected&&<div className="filter-bottom"><span>{[filter.type,filter.category,filter.supplier].filter(Boolean).map(v=><span className="chip" key={v}>{v}</span>)}</span><button className="text-button" onClick={()=>setFilter({type:'',category:'',supplier:'',search:''})}><X size={14}/> Effacer les filtres</button></div>}</section>
 {selected&&<div className="results"><section className="stats">{[{label:'Références sélectionnées',value:filtered.length,icon:<Boxes/>,color:'neutral'},{label:'Stock disponible',value:filtered.reduce((s,i)=>s+i.stock,0),icon:<Package/>,color:'neutral',small:new Set(filtered.map(i=>i.unit)).size>1?'Unités mixtes':''},{label:'Entrées cumulées',value:sum('incoming'),icon:<ArrowDownLeft/>,color:'green'},{label:'Sorties cumulées',value:sum('outgoing'),icon:<ArrowUpRight/>,color:'orange'}].map(s=><div className={`stat ${s.color}`} key={s.label}><span className="stat-icon">{s.icon}</span><div><small>{s.label}</small><strong>{s.value.toLocaleString('fr-FR')}</strong>{s.small&&<small>{s.small}</small>}</div></div>)}</section>
 <div className="result-toolbar"><div className="tabs"><button className={tab==='stock'?'active':''} onClick={()=>setTab('stock')}><Package size={17}/> Inventaire <span>{filtered.length}</span></button><button className={tab==='history'?'active':''} onClick={()=>setTab('history')}><History size={17}/> Mouvements</button></div><div className="export-actions"><button className="quiet" disabled={busy||!filtered.length} onClick={download}><Download size={16}/> PDF</button><button className="quiet" disabled={busy||!filtered.length} onClick={()=>open('email')}><Mail size={16}/> Envoyer</button><div className="view-toggle"><button aria-label="Vue cartes" className={view==='cards'?'active':''} onClick={()=>setView('cards')}><LayoutGrid size={17}/></button><button aria-label="Vue liste" className={view==='list'?'active':''} onClick={()=>setView('list')}><List size={17}/></button></div></div></div>
 {tab==='stock'?<>{!filtered.length?<div className="empty"><Package size={32}/><h3>Aucun article pour cette sélection</h3><p>Ajoutez votre première référence ou modifiez les filtres.</p><button className="primary" disabled={!online} onClick={()=>{setArticle({...blank,type:filter.type||blank.type,category:filter.category||blank.category,supplier:filter.supplier||blank.supplier});open('article');}}><Plus size={17}/> Ajouter un article</button></div>:<div className={`inventory ${view}`}>{filtered.map(i=>{const t=data.totals.find(t=>t.item_id===i.id);return <article className="item-card" key={i.id}><div className="item-top"><span className="item-icon"><Zap size={23}/></span><span className={`stock-status ${i.stock===0?'out':i.stock<=i.threshold?'low':''}`}><i/>{i.stock===0?'En rupture':i.stock<=i.threshold?'Stock faible':'Disponible'}</span><button className="icon-button edit" aria-label={`Modifier ${i.name}`} onClick={()=>{setArticle(i);open('article');}}><Pencil size={15}/></button></div><div className="item-title"><span className="reference">{i.ref}</span><h3>{i.name}</h3><p>{i.type} <span>·</span> {i.category}</p></div><div className="item-meta"><span>{i.supplier}</span>{i.location&&<span>{i.location}</span>}</div><div className="quantity"><strong>{i.stock.toLocaleString('fr-FR')}</strong><span>{i.unit}{i.stock>1&&i.unit==='pièce'?'s':''} en stock<small>Seuil d’alerte : {i.threshold}</small></span></div><div className="item-counters"><span><ArrowDownLeft size={15}/> {t?.incoming||0} entrées</span><span><ArrowUpRight size={15}/> {t?.outgoing||0} sorties</span></div><div className="item-actions"><button disabled={!online} onClick={()=>{setTarget(i);setKind('in');setQuantity(1);setNote('');open('movement');}}><Plus size={16}/> Entrée</button><button disabled={!online||!i.stock} onClick={()=>{setTarget(i);setKind('out');setQuantity(1);setNote('');open('movement');}}><ArrowUpRight size={16}/> Sortie</button></div></article>;})}</div>}</>:<div className="history-panel">{movements.length?<div className="table-wrap"><table><thead><tr><th>Date et heure</th><th>Article</th><th>Mouvement</th><th>Quantité</th><th>Motif</th></tr></thead><tbody>{movements.map(m=><tr key={m.id}><td>{new Date(m.created).toLocaleString('fr-FR')}</td><td><strong>{m.name}</strong><small>{m.ref}</small></td><td><span className={`badge ${m.kind==='in'?'green':'orange'}`}>{m.kind==='in'?'Entrée':'Sortie'}</span></td><td>{m.quantity} {m.unit}</td><td>{m.note||'—'}</td></tr>)}</tbody></table></div>:<div className="empty"><History size={30}/><h3>Aucun mouvement enregistré</h3></div>}<p className="history-note">Les 200 derniers mouvements du magasin sont disponibles dans cet historique. Les compteurs incluent tous les mouvements.</p></div>}
 <div className="result-footer"><span><RefreshCw size={12}/> Actualisation automatique toutes les 2 secondes</span><span>{filtered.filter(i=>i.stock<=i.threshold).length} référence(s) sous le seuil d’alerte</span></div></div>}
 </main></>}
 {toast&&<div className="toast" role="status"><Check size={18}/>{toast}</div>}
 {modal&&<div className="modal-backdrop" onClick={e=>{if(e.target===e.currentTarget&&!busy)setModal('');}}><section className={`modal ${modal==='article'?'wide':''}`} role="dialog" aria-modal="true" aria-labelledby="modal-title"><button className="modal-close" aria-label="Fermer" disabled={busy} onClick={()=>setModal('')}><X size={20}/></button>
 {modal==='article'&&<><div className="modal-symbol"><Package/></div><h2 id="modal-title">{article.id?'Modifier l’article':'Une nouvelle référence'}</h2><p className="modal-subtitle">Renseignez le matériel pour l’ajouter au magasin.</p><form onSubmit={e=>{e.preventDefault();mutate({action:article.id?'edit':'item',...article},article.id?'Article mis à jour.':'Article ajouté au magasin.');}}><div className="form-grid">{[{key:'name',label:'Désignation',placeholder:'Ex. Disjoncteur 16 A — 1P+N'},{key:'ref',label:'Référence',placeholder:'Référence fabricant'},{key:'type',label:'Type de matériel',list:typeOptions},{key:'category',label:'Catégorie',list:categoryOptions},{key:'supplier',label:'Fournisseur / fabricant',list:suppliers},{key:'unit',label:'Unité',list:['pièce','mètre','rouleau','boîte','lot']},{key:'location',label:'Emplacement (facultatif)',placeholder:'Ex. Rayon A · Bac 03'}].map(f=><label key={f.key}>{f.label}<input required={f.key!=='location'} maxLength={160} placeholder={f.placeholder} list={f.list?`list-${f.key}`:undefined} value={article[f.key]} onChange={e=>setArticle({...article,[f.key]:e.target.value})}/>{f.list&&<datalist id={`list-${f.key}`}>{f.list.map(v=><option key={v} value={v}/>)}</datalist>}</label>)}{!article.id&&<label>Stock initial<input type="number" min="0" max="10000000" required value={article.stock} onChange={e=>setArticle({...article,stock:Number(e.target.value)})}/></label>}<label>Seuil d’alerte<input type="number" min="0" max="10000000" required value={article.threshold} onChange={e=>setArticle({...article,threshold:Number(e.target.value)})}/></label></div>{article.id&&<p className="help">Pour modifier la quantité, enregistrez une entrée ou une sortie : chaque mouvement reste traçable.</p>}<Error message={error}/><button className="primary submit" disabled={busy}>{busy?'Enregistrement…':article.id?'Enregistrer les modifications':'Ajouter au magasin'}</button></form></>}
 {modal==='movement'&&target&&<><div className={`modal-symbol ${kind==='out'?'orange':''}`}>{kind==='in'?<ArrowDownLeft/>:<ArrowUpRight/>}</div><h2 id="modal-title">{kind==='in'?'Enregistrer une entrée':'Enregistrer une sortie'}</h2><p className="modal-subtitle">{target.name} · {target.ref}</p><div className="movement-stock">Stock actuel <strong>{data.items.find(i=>i.id===target.id)?.stock??target.stock} {target.unit}</strong></div><form onSubmit={e=>{e.preventDefault();mutate({action:'movement',id:target.id,kind,quantity,note},'Mouvement enregistré. Le stock est à jour.');}}><label>Quantité ({target.unit})<input type="number" autoFocus min="1" max={kind==='out'?(data.items.find(i=>i.id===target.id)?.stock??target.stock):10000000} required value={quantity} onChange={e=>setQuantity(Number(e.target.value))}/></label><label>Motif / destinataire (facultatif)<textarea maxLength={400} placeholder="Livraison, atelier, chantier…" value={note} onChange={e=>setNote(e.target.value)}/></label><Error message={error}/><button className="primary submit" disabled={busy}>{busy?'Enregistrement…':'Confirmer le mouvement'}</button></form></>}
 {modal==='admin'&&data.admin&&<><div className="modal-symbol"><LockKeyhole/></div><h2 id="modal-title">Votre établissement</h2><p className="modal-subtitle">Ces informations apparaîtront sur vos exports PDF.</p><form onSubmit={e=>{e.preventDefault();mutate({action:'settings',...school},'Établissement enregistré.',false);}}><label>Nom de l’établissement<input required maxLength={160} value={school.name} onChange={e=>setSchool({...school,name:e.target.value})}/></label><label>Adresse complète<textarea required maxLength={800} value={school.address} onChange={e=>setSchool({...school,address:e.target.value})}/></label><label>Logo de l’établissement (facultatif)<input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>logoUpload(e.target.files?.[0])}/></label>{school.logo&&<div className="logo-preview"><img src={school.logo} alt="Logo de l’établissement"/><button type="button" className="text-button" onClick={()=>setSchool({...school,logo:''})}>Retirer</button></div>}<button className="primary submit" disabled={busy}>Enregistrer l’établissement</button></form><div className="admin-extra"><h3>Accès au magasin</h3><p className="help">Autorisez une adresse, puis demandez à cette personne de créer son compte et de configurer Authenticator. Aucun mot de passe n’est partagé.</p><form onSubmit={async e=>{e.preventDefault();if(await mutate({action:'member',email:memberEmail,role:memberRole},'Adresse autorisée.',false))setMemberEmail('');}}><label>Adresse e-mail<input type="email" required value={memberEmail} onChange={e=>setMemberEmail(e.target.value)}/></label><label>Rôle<select value={memberRole} onChange={e=>setMemberRole(e.target.value)}><option value="team">Équipe</option><option value="admin">Administrateur</option></select></label><button className="primary submit" disabled={busy}>Autoriser cet accès</button></form>{data.members.map(m=><div className="factor-row" key={m.email}><span>{m.email}<small>{m.role==='admin'?'Administrateur':'Équipe'} · {m.active?'Actif':'Désactivé'}</small></span>{m.active&&<button className="quiet" disabled={busy} onClick={()=>mutate({action:'remove_member',email:m.email},'Accès désactivé.',false)}>Désactiver</button>}</div>)}</div><Error message={error}/></>}
 {modal==='email'&&<><div className="modal-symbol"><Mail/></div><h2 id="modal-title">Transmettre l’inventaire</h2><p className="modal-subtitle">Le PDF contient les {filtered.length} références sélectionnées et les informations de votre établissement.</p><form onSubmit={send}><label>Adresse e-mail du destinataire<input type="email" required value={recipient} onChange={e=>setRecipient(e.target.value)} placeholder="destinataire@etablissement.fr"/></label><div className="help-box"><Download size={18}/><p>Le PDF sera téléchargé et votre messagerie s’ouvrira. Ajoutez le fichier en pièce jointe avant d’envoyer. Sur les appareils compatibles, le partage du PDF est proposé directement.</p></div><Error message={error}/><button className="primary submit" disabled={busy}>{busy?'Préparation…':'Préparer le PDF et le message'}</button></form></>}
 </section></div>}
 </div>;
}
function Error({message}:{message:string}){return message?<p className="form-error" role="alert"><AlertTriangle size={16}/>{message}</p>:null;}





